name: video_vector
channels:
  - pytorch
  - nvidia
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2024.12.31
  - cuda-cudart=12.4.127
  - cuda-cupti=12.4.127
  - cuda-libraries=12.4.1
  - cuda-nvrtc=12.4.127
  - cuda-nvtx=12.4.127
  - cuda-opencl=12.6.77
  - cuda-runtime=12.4.1
  - cuda-version=12.6
  - expat=2.6.4
  - freetype=2.12.1
  - giflib=5.2.2
  - gmp=6.2.1
  - gnutls=3.6.15
  - intel-openmp=2023.1.0
  - jinja2=3.1.4
  - jpeg=9e
  - lame=3.100
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libcublas=12.4.5.8
  - libcufft=11.2.1.3
  - libcufile=1.11.1.6
  - libcurand=10.3.7.77
  - libcusolver=11.6.1.9
  - libcusparse=12.3.1.170
  - libdeflate=1.22
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - libnpp=12.2.5.30
  - libnvfatbin=12.6.77
  - libnvjitlink=12.4.127
  - libnvjpeg=12.3.1.117
  - libpng=1.6.39
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mpmath=1.3.0
  - ncurses=6.4
  - nettle=3.7.3
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openssl=3.0.15
  - pip=24.2
  - pysocks=1.7.1
  - python=3.12.8
  - pytorch=2.5.0
  - pytorch-cuda=12.4
  - pytorch-mutex=1.0
  - pyyaml=6.0.2
  - readline=8.2
  - requests=2.32.3
  - setuptools=75.1.0
  - sqlite=3.45.3
  - tbb=2021.8.0
  - tk=8.6.14
  - torchaudio=2.5.0
  - torchtriton=3.1.0
  - torchvision=0.20.0
  - typing_extensions=4.12.2
  - urllib3=2.2.3
  - wheel=0.44.0
  - xz=5.4.6
  - yaml=0.2.5
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - addict==2.4.0
      - aiofiles==24.1.0
      - aiohappyeyeballs==2.4.3
      - aiohttp==3.10.10
      - aiokubernetes==0.6
      - aioredis==2.0.1
      - aiosignal==1.3.1
      - altair==5.4.1
      - amqp==5.3.1
      - annotated-types==0.7.0
      - anyio==3.7.1
      - apscheduler==3.11.0
      - argcomplete==3.5.1
      - asgiref==3.8.1
      - asttokens==3.0.0
      - async-timeout==5.0.1
      - asyncpg==0.30.0
      - attrs==24.2.0
      - bcrypt==4.3.0
      - beautifulsoup4==4.12.3
      - billiard==4.2.1
      - blinker==1.8.2
      - blis==1.2.0
      - boto3==1.35.45
      - botocore==1.35.45
      - brotli==1.1.0
      - build==1.2.2.post1
      - cachetools==5.5.0
      - catalogue==2.0.10
      - celery==5.4.0
      - certifi==2024.8.30
      - cffi==1.17.1
      - charset-normalizer==3.4.0
      - click==8.1.7
      - click-didyoumean==0.3.1
      - click-plugins==1.1.1
      - click-repl==0.3.0
      - cloudpathlib==0.20.0
      - confection==0.1.5
      - contourpy==1.3.0
      - cryptography==44.0.3
      - cycler==0.12.1
      - cymem==2.0.10
      - dacite==1.7.0
      - dataclasses-json==0.6.7
      - datasets==3.3.2
      - dateparser==1.2.1
      - decorator==4.4.2
      - deprecated==1.2.14
      - dill==0.3.8
      - distro==1.9.0
      - dnspython==2.3.0
      - dukpy==0.4.0
      - durationpy==0.9
      - easyocr==1.7.2
      - eventlet==0.39.1
      - executing==2.2.0
      - fastapi==0.103.2
      - ffmpeg==1.4
      - fiftyone==1.0.1
      - fiftyone-brain==0.17.0
      - fiftyone-db==1.1.7
      - filelock==3.16.1
      - flask==3.0.3
      - flask-cors==5.0.0
      - flower==2.0.1
      - fonttools==4.54.1
      - frozenlist==1.4.1
      - fsspec==2024.10.0
      - ftfy==6.3.0
      - future==1.0.0
      - gevent==24.11.1
      - gitdb==4.0.11
      - gitpython==3.1.43
      - glob2==0.7
      - google-auth==2.38.0
      - graphql-core==3.2.5
      - greenlet==3.1.1
      - h11==0.14.0
      - h2==4.1.0
      - hpack==4.0.0
      - httmock==1.4.0
      - httpcore==1.0.6
      - httpx==0.27.2
      - huggingface-hub==0.26.1
      - humanize==4.11.0
      - hypercorn==0.17.3
      - hyperframe==6.0.1
      - idna==3.10
      - imageio==2.9.0
      - imageio-ffmpeg==0.4.7
      - inflate64==1.0.0
      - ipython==9.2.0
      - ipython-pygments-lexers==1.1.1
      - itsdangerous==2.2.0
      - jedi==0.19.2
      - jiter==0.6.1
      - jmespath==1.0.1
      - joblib==1.4.2
      - jsonlines==4.0.0
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - kaleido==0.2.1
      - kiwisolver==1.4.7
      - kombu==5.5.0
      - kubernetes==32.0.1
      - kubernetes-asyncio==32.0.0
      - langchain==0.3.4
      - langchain-community==0.3.3
      - langchain-core==0.3.12
      - langchain-openai==0.2.3
      - langchain-text-splitters==0.3.0
      - langcodes==3.5.0
      - langsmith==0.1.137
      - language-data==1.3.0
      - lazy-loader==0.4
      - llvmlite==0.43.0
      - marisa-trie==1.2.1
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - marshmallow==3.23.0
      - matplotlib==3.9.2
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - modelscope==1.25.0
      - mongoengine==0.24.2
      - more-itertools==10.5.0
      - motor==3.5.3
      - moviepy==1.0.3
      - multidict==6.1.0
      - multiprocess==0.70.16
      - multivolumefile==0.2.3
      - murmurhash==1.0.11
      - mutagen==1.47.0
      - mutf8==1.0.6
      - mypy-extensions==1.0.0
      - narwhals==1.10.0
      - networkx==3.4.1
      - ninja==1.11.1.3
      - numba==0.60.0
      - numpy==1.26.4
      - oauthlib==3.2.2
      - openai==1.52.1
      - openai-whisper==20240930
      - opencv-python-headless==4.10.0.84
      - orjson==3.10.10
      - outcome==1.3.0.post0
      - packaging==24.2
      - pandas==2.2.3
      - paramiko==3.5.1
      - parso==0.8.4
      - pdf2image==1.17.0
      - pexpect==4.9.0
      - pgvector==0.3.5
      - pillow==10.4.0
      - pillow-heif==0.20.0
      - pip-tools==7.4.1
      - plotly==5.24.1
      - pprintpp==0.4.0
      - preshed==3.0.9
      - priority==2.0.0
      - proglog==0.1.11
      - prometheus-api-client==0.6.0
      - prometheus-client==0.21.1
      - prompt-toolkit==3.0.50
      - propcache==0.2.0
      - protobuf==5.28.3
      - psutil==6.1.0
      - psycopg2-binary==2.9.10
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - py7zr==0.22.0
      - pyarrow==17.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pybcj==1.0.2
      - pyclipper==1.3.0.post6
      - pycocotools==2.0.8
      - pycparser==2.22
      - pycryptodomex==3.21.0
      - pydantic==2.9.2
      - pydantic-core==2.23.4
      - pydantic-settings==2.6.0
      - pydash==8.0.3
      - pydeck==0.9.1
      - pydub==0.25.1
      - pygments==2.18.0
      - pymongo==4.8.0
      - pynacl==1.5.0
      - pyparsing==3.2.0
      - pypdf2==3.0.1
      - pyppmd==1.1.0
      - pyproject-hooks==1.2.0
      - python-bidi==0.6.6
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - python-multipart==0.0.20
      - pytube==15.0.0
      - pytubefix==6.6.3
      - pytz==2024.2
      - pyzstd==0.16.2
      - rarfile==4.2
      - redis==5.2.1
      - referencing==0.35.1
      - regex==2024.9.11
      - requests-oauthlib==2.0.0
      - requests-toolbelt==1.0.0
      - retrying==1.3.4
      - rich==13.9.3
      - rpds-py==0.20.0
      - rsa==4.9
      - s3transfer==0.10.3
      - safetensors==0.4.5
      - scikit-image==0.24.0
      - scikit-learn==1.5.2
      - scipy==1.14.1
      - scp==0.15.0
      - selenium==4.25.0
      - sentence-transformers==3.2.1
      - sentencepiece==0.2.0
      - shapely==2.0.7
      - shellingham==1.5.4
      - six==1.17.0
      - smart-open==7.0.5
      - smmap==5.0.1
      - sniffio==1.3.1
      - sortedcontainers==2.4.0
      - soupsieve==2.6
      - spacy==3.8.4
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - sqlalchemy==2.0.36
      - srsly==2.4.8
      - sse-starlette==0.10.3
      - sseclient-py==1.8.0
      - stack-data==0.6.3
      - starlette==0.27.0
      - strawberry-graphql==0.247.0
      - streamlit==1.39.0
      - sympy==1.13.1
      - tabulate==0.9.0
      - tenacity==9.0.0
      - termcolor==2.5.0
      - texttable==1.7.0
      - thinc==8.3.4
      - threadpoolctl==3.5.0
      - tifffile==2024.9.20
      - tiktoken==0.8.0
      - tokenizers==0.20.1
      - toml==0.10.2
      - tornado==6.4.2
      - tqdm==4.66.5
      - traitlets==5.14.3
      - transformers==4.45.2
      - trio-websocket==0.11.1
      - typer==0.15.1
      - typing-inspect==0.9.0
      - tzdata==2025.1
      - tzlocal==5.2
      - universal-analytics-python3==1.1.1
      - uvicorn==0.34.0
      - vine==5.1.0
      - voxel51-eta==0.13.0
      - wasabi==1.1.3
      - watchdog==5.0.3
      - wcwidth==0.2.13
      - weasel==0.4.1
      - websocket-client==1.8.0
      - websockets==13.1
      - webuiapi==0.9.16
      - webvtt-py==0.5.1
      - werkzeug==3.0.4
      - wrapt==1.16.0
      - wsproto==1.2.0
      - xmltodict==0.14.2
      - xxhash==3.5.0
      - yarl==1.16.0
      - you-get==0.4.1730
      - youtube-dl==2025.4.7
      - yt-dlp==2024.10.22
      - zope-event==5.0
      - zope-interface==7.2
